apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kube
  template:
    metadata:
      labels:
        app: hello-kube
    spec:
      containers:
        - name: hello-kube
          image: hello-kube:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000